version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-actual-budget_server_1
      APP_PORT: 5006

  server:
    image: actualbudget/actual-server:latest-alpine
    container_name: sparkles-actual-budget_server
    user: "1000:1000"
    init: true
    volumes:
      - actual_data:/data
    restart: unless-stopped

volumes:
  actual_data:
